name: Python Tests

on:
  push:
    branches: [ master, develop ] # Run on pushes to master and develop branches
  pull_request:
    branches: [ master, develop ] # Run on pull requests to master and develop branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update 
          sudo apt-get install -y libxml2-dev libxslt-dev python3-dev exuberant-ctags
          pip install -r requirements.txt
          pip install flake8

      - name: Run tests
        run: make test
